---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-test-pod
    image: nginx:stable
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx
      readOnly: true
      name: nginx-conf
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
        - key: nginx.conf
          path: nginx.conf
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-chat
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80
